# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d25b6435f2dad9eca3d0bec1887f0d99e0083266aab88336e1f70b420323ab4d70e85310275d5c4642b86e6b700be861bd69d9af4c3cc81a1ba2f0f0916229ea

test:
  secret_key_base: bb6a8c4440f2da13b83c87bd65bbcd0109058fd86096bb529df66c6cfcda0119255e110887858a1f2540ff986ca49cefaf055b45543ee07b36294313bfe2f1f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
